version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: 'meteor_app'
    container_name: 'meteor_app'
    stdin_open: true
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://oxide:27017/meteor
      PORT: 3000
  nginx:
    image: nginx
    hostname: 'nginx'
    container_name: 'nginx'
    ports:
      - 8888:8888
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  postgres:
    image: postgres:14.0
    hostname: 'postgres'
    container_name: 'postgres'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=meteor
  oxide:
    build: https://github.com/fcoury/oxide.git
    hostname: 'oxide'
    container_name: 'oxide'
    restart: 'on-failure'
    command:
      [
        '/target/release/oxide',
        '--web',
        '--postgres-url=postgres://postgres@postgres:5432/meteor',
      ]
    ports:
      - 27017:27017
      - 8087:8087
    depends_on:
      - 'postgres'
  setup:
    image: postgres:14.0
    hostname: 'setup'
    container_name: 'setup'
    restart: 'on-failure'
    depends_on:
      - 'postgres'
    entrypoint: ["sh", "-c", "psql -h postgres -U postgres -d meteor -c 'CREATE SCHEMA IF NOT EXISTS tasks'"]
